[build]
    command = "hugo"
    publish = "public"
    functions = "functions"

[context.production.environment]
    HUGO_VERSION = "0.112.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "https://aaronreding.ie/*"
to = "https://aaronreding.net/:splat"
status = 301
force = true
[[redirects]]
from = "https://www.aaronreding.ie/*"
to = "https://aaronreding.net/:splat"
status = 301
force = true
